namely_employees_app/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/namely/auth' => 'namely#auth'
  get '/namely/auth_callback' => 'namely#auth_callback'
  resources :employees
end

namely_employees_app/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    if params[:sort_first_name]
      response = auth_data.get('https://verner-eng-homework.namely.com/api/v1/profiles.json?sort=first_name')
    else
      response = auth_data.get('https://verner-eng-homework.namely.com/api/v1/profiles.json?limit=all')
    end
    @data = JSON.parse(response.body)
  end

  private

  def auth_data
    auth_code = session['oauth_access_code']
    token = NamelyOauth.oauth_client.auth_code.get_token(auth_code,
      :redirect_uri => NamelyOauth.redirect_url)
  end

end

namely_employees_app/app/views/employees/_employees_table.html.erb
<h1>This is the employees table</h1>

<a href="<%= employees_path(:sort_first_name => true) %>" class="btn btn-primary"> Sort by First Name</a>
<table class="table">
    <thead>
      <tr>
        <th> First Name</a></th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Job Title</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%@data["profiles"].each do |profile| %>
      <tr>
        <td><%= profile["first_name"] %></td>
        <td><%= profile["last_name"] %></td>
        <td><%= profile["email"] %></td>
        <td><%= profile["job_title"]["title"] %></td>
        <td><%= profile["user_status"] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>