namely_employees_app_verner/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/namely/auth' => 'namely#auth'
  get '/namely/auth_callback' => 'namely#auth_callback'
  get '/employees/sort_employees' => 'employees#sort_employees'
  resources :employees
end

namely_employees_app_verner/app/models/employee.rb
class Employee < ActiveRecord::Base
end

namely_employees_app_verner/app/models/namely_oauth.rb
class NamelyOauth

  def self.oauth_client
    OAuth2::Client.new(Rails.application.secrets.namely_oauth_client_id,
      Rails.application.secrets.namely_oauth_secret,
      :authorize_url => '/api/v1/oauth2/authorize',
      :token_url => '/api/v1/oauth2/token',
      :site => 'https://verner-eng-homework.namely.com')
  end

  def self.redirect_url
    'http://localhost:3000/namely/auth_callback'
  end

end

namely_employees_app_verner/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

namely_employees_app_verner/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    response = auth_data.get('https://verner-eng-homework.namely.com/api/v1/profiles.json?limit=all')
    @data = JSON.parse(response.body)
  end

  def sort_employees
    response = auth_data.get('https://verner-eng-homework.namely.com/api/v1/profiles.json?sort=first_name')
    @data = JSON.parse(response.body)
  end

  private

  def auth_data
    auth_code = session['oauth_access_code']
    token = NamelyOauth.oauth_client.auth_code.get_token(auth_code,
      :redirect_uri => NamelyOauth.redirect_url)
  end

end

namely_employees_app_verner/app/controllers/namely_controller.rb
class NamelyController < ApplicationController

  def auth
    url = NamelyOauth.oauth_client.auth_code.authorize_url(:redirect_uri => NamelyOauth.redirect_url)
    redirect_to url
  end

  def auth_callback
    auth_code = params[:code]
    token = NamelyOauth.oauth_client.auth_code.get_token(auth_code,
      :redirect_uri => NamelyOauth.redirect_url)
    session['oauth_access_code'] = auth_code
    redirect_to employees_path
  end


end

namely_employees_app_verner/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

namely_employees_app_verner/app/helpers/application_helper.rb
module ApplicationHelper
end

namely_employees_app_verner/app/views/employees/_employees_table.html.erb
<h1>This is the employees table</h1>

<a href="<%= employees_sort_employees_path %>" class="btn btn-primary"> Sort by First Name</a>
<table class="table">
    <thead>
      <tr>
        <th> First Name</a></th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Job Title</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%@data["profiles"].each do |profile| %>
      <tr>
        <td><%= profile["first_name"] %></td>
        <td><%= profile["last_name"] %></td>
        <td><%= profile["email"] %></td>
        <td><%= profile["job_title"]["title"] %></td>
        <td><%= profile["user_status"] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

namely_employees_app_verner/app/views/employees/index.html.erb
<%= render partial: "employees_table" %>

namely_employees_app_verner/app/views/employees/sort_employees.html.erb
<%= render partial: "employees_table" %>

namely_employees_app_verner/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NamelyEmployeesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%#= yield %>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Namely Employees App', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">

      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

namely_employees_app_verner/app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate with Namely to get started.</p>
  <a href="<%= namely_auth_path %>" class="btn btn-primary">Log In with Namely</a>
</div>

namely_employees_app_verner/app/views/pages/success.html.erb
<h1>Once authentication is complete you will come back to this page</h1>